services:
  # Service PHP + Apache
  php:
    image: php:8.2-apache
    platform: linux/arm64
    container_name: rpg_php
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql mysqli
      && a2enmod rewrite
      && apache2-foreground"

  # Service MySQL
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: rpg_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rpg_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

# Volume pour persister les donn√©es MySQL
volumes:
  mysql_data:
